name: Vita Prepare for Pull Request

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download repository
      uses: actions/checkout@v2

    - name: Deleted generated files
      env:
         token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        github/deleteGeneratedFiles.perl $GITHUB_REPOSITORY $token
