name: Vita Prepare for Pull Request

on:
  push:
    paths:
    - ".github/control/prepareForPullRequest.txt"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download repository
      uses: actions/checkout@v2

    - name: Install software packages
      run: |
        sudo cpan install Data::Table::Text GitHub::Crud Data::Dump

    - name: Deleted and refresh generated files
      env:
         token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        perl github/deleteGeneratedFiles.pl $GITHUB_REPOSITORY $token
